### ISSUE TITLE
Game- BrickBreakerPong(1)-Add Sounds

### ISSUE THREAD

**Issue by CoderCatA5** [CoderCatA5/MADKAUSING-C-Gamedev#12]
## ADD GAME SOUNDS ON IMPACT
- add game sounds when the ball collides
- refer to raylib. for instructions
# Bounty Points

20 points

**Comment by Aspireve** [comment]
Hey @CoderCatA5 Could I work on this issue?

**Comment by CoderCatA5** [comment]
Hey @Aspireve the project is currently available on windows only. 
Just run the scripts in the scripts folder
Hopefully it should work

**Comment by Aspireve** [comment]
Hi @CoderCatA5 
I tried running the commands based on what is written in the ReadMe.md but it doesn't seem to work (I use Windows only)
When I run it in terminal I get this screen open
![image](https://user-images.githubusercontent.com/93852415/197711174-e2f27994-538e-47b4-a2e3-0c3b2f5cd382.png)
And when I manually open it it shows my terminal screen for 2-3 sec and then closes it
